# Site settings
title: ROME
header-img: img/rome.jpg
email: slankes@eonerc.rwth-aachen.de
description: "Workshop on Runtime and Operating Systems for the Many-core Era"
#baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://yourdomain.com"
#twitter_username: SBootstrap
#github_username:  davidtmiller
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["LICENSE", "less","node_modules","Gruntfile.js","package.json","README.md"]
