# Site settings
title: ROME
header-img: img/rome.jpg
email: slankes@eonerc.rwth-aachen.de
description: "Workshops on Runtime and Operating Systems for the Many-core Era"
url: http://wrome.github.io
#twitter_username: SBootstrap
#github_username:  davidtmiller
#facebook_username:  IronSummitMedia

# Build settings
#markdown: kramdown
#kramdown:
#   input: GFM
#   hard_wrap: false
#markdown: redcarpet
#redcarpet:
#  extensions: ["strikethrough"]
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["LICENSE", "less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]
